# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque_action_mailer_backend}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maur\303\255cio Linhares"]
  s.date = %q{2011-01-16}
  s.description = %q{
      With this gem you will be able to enqueue your emails
      on your Resque workers to avoid making your user wait for the email to be
      send when he causes an email sending action in your application.

      Using resque_action_mailer_backend makes email sending a breeze as
      you will be able to use Resque to retry failed emails, easily deliver all
      those marketing emails to your clients and without changing anything at
      your email sending code.

      Just tell your application to use :resque for sending emails and you're done,
      no need to add yet another tool just for delivering your emails if you're
      already using Resque for your asynchronous processing.
    }
  s.email = %q{mauricio.linhares@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CHANGELOG",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/headbanger/resque_mailer.rb",
    "lib/init.rb",
    "lib/resque_action_mailer_backend.rb",
    "resque_action_mailer_backend.gemspec",
    "spec/resque_action_mailer_backend_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/test_mailer.rb",
    "spec/test_mailer/test.erb"
  ]
  s.homepage = %q{http://github.com/mauricio/resque_action_mailer_backend}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{resque_action_mailer_backend}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Use Resque to enqueue and send your emails}
  s.test_files = [
    "spec/resque_action_mailer_backend_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_mailer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, [">= 1.8.0"])
      s.add_runtime_dependency(%q<actionmailer>, [">= 2.2.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<resque>, [">= 1.8.0"])
      s.add_dependency(%q<actionmailer>, [">= 2.2.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<resque>, [">= 1.8.0"])
    s.add_dependency(%q<actionmailer>, [">= 2.2.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

